### ISSUE TITLE
Fighter Plugin Throws AbstractMethodError if loot csv is provided

### ISSUE THREAD

**Issue by jalexb** [MeteorLite/meteor-client#97]
This error is thrown when an item is found on the ground that is in the list of items to be picked up.

Example:
I'm killing ammonite crabs and want to pickup Numulite. When numulite is dropped and the player is finished fighting, the Client throws this Exception and you have to hard reset the client to run the game again.

```
Exception in thread "Client" java.lang.AbstractMethodError: Receiver class cr does not define or inherit an implementation of the resolved method 'abstract void setIndex(int)' of interface net.runelite.api.TileItem.
	at net.runelite.api.TileItem.interact(TileItem.kt:106)
	at meteor.plugins.fighter.FighterPlugin.onGameTick(FighterPlugin.kt:94)
	at meteor.plugins.EventSubscriber$subscribeEvents$26$1.invoke(EventSubscriber.kt:178)
	at meteor.plugins.EventSubscriber$subscribeEvents$26$1.invoke(EventSubscriber.kt:178)
	at meteor.plugins.EventSubscriber.executeIfListening(EventSubscriber.kt:107)
	at meteor.plugins.EventSubscriber$subscribeEvents$26.invoke(EventSubscriber.kt:178)
	at meteor.plugins.EventSubscriber$subscribeEvents$26.invoke(EventSubscriber.kt:178)
	at meteor.plugins.EventSubscriber$subscribeEvents$$inlined$subscribeEvent$26.invoke(EventSubscriber.kt:343)
	at meteor.plugins.EventSubscriber$subscribeEvents$$inlined$subscribeEvent$26.invoke(EventSubscriber.kt:343)
	at org.rationalityfrontline.kevent.KEvent.post(KEvent.kt:676)
	at meteor.Hooks.tick(Hooks.kt:351)
	at client.doCycle(Client.java:2690)
	at client.an(Client.java)
	at an.ao(GameEngine.java:390)
	at an.run(GameEngine.java:369)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by BloatGoat** [comment]
This issue should be fixed in the latest version.
